#!/bin/bash

clear
echo "╔════════════════════════════════════════════════╗"
echo "║                                                ║"
echo "║    Audex DEB Package - Interactive Test       ║"
echo "║                                                ║"
echo "╚════════════════════════════════════════════════╝"
echo ""
echo "📦 Package ready: /tmp/audex.deb"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 Quick Start Commands:"
echo ""
echo "  # 1. Install package"
echo "  sudo dpkg -i /tmp/audex.deb"
echo "  sudo apt-get install -f"
echo ""
echo "  # 2. Verify installation"
echo "  which audex"
echo "  which audex-setup"
echo ""
echo "  # 3. Check files"
echo "  ls -la /etc/audex/"
echo "  tree /usr/lib/audex/"
echo ""
echo "  # 4. View configurations"
echo "  cat /etc/audex/config.system.yml"
echo "  cat /etc/audex/config.example.yml"
echo ""
echo "  # 5. Initialize user"
echo "  audex-setup"
echo ""
echo "  # 6.  Check user files"
echo "  ls -la ~/.local/share/audex/"
echo "  ls -la ~/.config/audex/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Tips:"
echo "  - Type 'guide' anytime to see this message"
echo "  - Type 'exit' to leave the container"
echo ""
