#!/bin/bash
# ============================================================================
# Audex DEB Package - Interactive Test Guide (System Mode)
# ============================================================================

clear
echo "╔════════════════════════════════════════════════╗"
echo "║                                                ║"
echo "║    Audex DEB Package - Interactive Test        ║"
echo "║           (System Mode - Root Required)        ║"
echo "║                                                ║"
echo "╚════════════════════════════════════════════════╝"
echo ""
echo "📦 Package ready: /tmp/audex.deb"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 Installation & Testing:"
echo ""
echo "  # 1️⃣  Install the package"
echo "  dpkg -i /tmp/audex.deb"
echo "  apt-get install -f"
echo ""
echo "  # 2️⃣  Verify installation"
echo "  which audex"
echo "  which audex-setup"
echo "  systemctl status audex. service"
echo ""
echo "  # 3️⃣  Check system directories"
echo "  ls -la /etc/audex/"
echo "  ls -la /var/lib/audex/"
echo "  ls -la /var/log/audex/"
echo "  tree /usr/lib/audex/"
echo ""
echo "  # 4️⃣  View generated configurations"
echo "  cat /etc/audex/config.system. yml"
echo "  cat /etc/audex/config.example.yml"
echo ""
echo "  # 5️⃣  Run setup wizard (interactive)"
echo "  audex-setup"
echo ""
echo "  # 6️⃣  Check main configuration"
echo "  cat /etc/audex/config.yml"
echo ""
echo "  # 7️⃣  Test manual start"
echo "  audex --help"
echo "  audex --version"
echo ""
echo "  # 8️⃣  Test systemd service"
echo "  systemctl enable audex.service"
echo "  systemctl start audex.service"
echo "  systemctl status audex.service"
echo ""
echo "  # 9️⃣  View logs"
echo "  journalctl -u audex.service -n 50"
echo "  tail -f /var/log/audex/audex.log"
echo ""
echo "  # 🔟 Stop service"
echo "  systemctl stop audex.service"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🗑️  Uninstallation:"
echo ""
echo "  # Remove package (keep config)"
echo "  apt-get remove audex"
echo ""
echo "  # Remove package and config"
echo "  apt-get purge audex"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Tips:"
echo "  - Type 'guide' to see this message again"
echo "  - All operations require root (no sudo needed in container)"
echo "  - System paths:"
echo "    • Config:  /etc/audex/"
echo "    • Data:    /var/lib/audex/"
echo "    • Logs:    /var/log/audex/"
echo "  - Type 'exit' to leave the container"
echo ""
